export const SHOW_LOGIN_DIALOG = 'SHOW_LOGIN_DIALOG'
export const HIDE_LOGIN_DIALOG = 'HIDE_LOGIN_DIALOG'
export const SHOW_SIGNUP_DIALOG = 'SHOW_SIGNUP_DIALOG'
export const HIDE_SIGNUP_DIALOG = 'HIDE_SIGNUP_DIALOG'
